export default [
  {
    _id: "A101",
    title: "Propulsion Fundamentals",
    course: "RS101",
    available: "2026-01-20T00:00",
    due: "2026-02-03T23:59",
    until: "2026-02-03T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Review the core principles of rocket propulsion including Newton's third law, specific impulse, and the rocket equation. Submit a written analysis comparing the efficiency of liquid, solid, and hybrid propellant systems, supported by calculations.",
  },
  {
    _id: "A102",
    title: "Combustion Analysis",
    course: "RS101",
    available: "2026-02-10T00:00",
    due: "2026-02-24T23:59",
    until: "2026-03-03T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: true,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Analyze the combustion characteristics of a given propellant combination. Using provided datasets, calculate the adiabatic flame temperature, exhaust velocity, and identify potential combustion instabilities. Present your findings in a structured technical report.",
  },
  {
    _id: "A103",
    title: "Nozzle Design Project",
    course: "RS101",
    available: "2026-03-10T00:00",
    due: "2026-03-31T23:59",
    until: "2026-04-07T23:59",
    points: 150,
    group: "PROJECTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: true,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Design a converging-diverging nozzle for a specified thrust requirement. Your submission must include the nozzle geometry calculations, an analysis of flow conditions at the throat and exit, and a discussion of trade-offs between performance and manufacturability.",
  },
  {
    _id: "A201",
    title: "Airfoil Aerodynamics Quiz",
    course: "RS102",
    available: "2026-01-27T00:00",
    due: "2026-02-10T23:59",
    until: "2026-02-10T23:59",
    points: 50,
    group: "QUIZZES",
    gradeType: "RAW_TOTAL",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Complete the online quiz covering airfoil geometry, angle of attack, boundary layer behavior, and the relationship between camber and lift coefficient. Questions are drawn from Chapters 1–3 of the course text.",
  },
  {
    _id: "A202",
    title: "Lift and Drag Analysis",
    course: "RS102",
    available: "2026-02-17T00:00",
    due: "2026-03-03T23:59",
    until: "2026-03-10T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: true,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Using wind tunnel data provided in the course portal, calculate the lift-to-drag ratio for three airfoil profiles across a range of angles of attack. Identify the optimal cruise condition for each profile and justify your selection in a short written summary.",
  },
  {
    _id: "A203",
    title: "Supersonic Flow Report",
    course: "RS102",
    available: "2026-03-17T00:00",
    due: "2026-04-07T23:59",
    until: "2026-04-14T23:59",
    points: 125,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Investigate the behavior of airflow at supersonic speeds, including shock wave formation, wave drag, and the Prandtl-Glauert singularity. Write a technical report that includes hand calculations and discusses the design implications for high-speed aircraft and re-entry vehicles.",
  },
  {
    _id: "A301",
    title: "Structural Load Analysis",
    course: "RS103",
    available: "2026-01-22T00:00",
    due: "2026-02-05T23:59",
    until: "2026-02-05T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Perform a structural load analysis for a simplified spacecraft bus under launch conditions. Identify critical load cases, calculate stress and deflection for key structural members, and recommend materials based on mass and strength constraints.",
  },
  {
    _id: "A302",
    title: "Orbital Mechanics Problem Set",
    course: "RS103",
    available: "2026-02-12T00:00",
    due: "2026-02-26T23:59",
    until: "2026-02-26T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Solve a set of problems covering Kepler's laws, Hohmann transfers, and orbital insertion burns. Show all work and include a brief written explanation of each solution strategy. Problems are available in the course portal under Module 4.",
  },
  {
    _id: "A303",
    title: "Thermal Control System Design",
    course: "RS103",
    available: "2026-03-12T00:00",
    due: "2026-04-02T23:59",
    until: "2026-04-09T23:59",
    points: 150,
    group: "PROJECTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: true,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Design a passive thermal control system for a small satellite operating in low Earth orbit. Your report must include a thermal model, analysis of hot and cold case scenarios, and a description of selected coatings, insulation, and heat dissipation strategies.",
  },
  {
    _id: "A401",
    title: "Functional Group Identification",
    course: "RS104",
    available: "2026-01-20T00:00",
    due: "2026-02-03T23:59",
    until: "2026-02-03T23:59",
    points: 75,
    group: "ASSIGNMENTS",
    gradeType: "RAW_TOTAL",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: true,
    },
    assignTo: "Everyone",
    description:
      "Given a set of unknown organic compounds and their IR and NMR spectra, identify the functional groups present in each structure. Provide a written justification for each identification, referencing specific spectral peaks and their corresponding molecular features.",
  },
  {
    _id: "A402",
    title: "Reaction Mechanisms Problem Set",
    course: "RS104",
    available: "2026-02-10T00:00",
    due: "2026-02-24T23:59",
    until: "2026-03-03T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: true,
    },
    assignTo: "Everyone",
    description:
      "Draw the complete arrow-pushing mechanisms for a series of organic reactions including SN1, SN2, E1, E2, and electrophilic addition. For each, identify the rate-determining step and predict the major product, including stereochemical outcomes where applicable.",
  },
  {
    _id: "A403",
    title: "Organic Synthesis Lab Report",
    course: "RS104",
    available: "2026-03-10T00:00",
    due: "2026-03-31T23:59",
    until: "2026-04-14T23:59",
    points: 100,
    group: "LAB_REPORTS",
    gradeType: "PERCENTAGE",
    submissionType: "IN_PERSON",
    onlineEntryOptions: {
      textEntry: false,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Write a formal lab report for the multi-step synthesis performed in weeks 6–7. Your report must include a purpose statement, balanced reaction equations, a description of purification techniques used, percent yield calculations, and an analysis of potential sources of error.",
  },
  {
    _id: "A501",
    title: "Coordination Compounds Analysis",
    course: "RS105",
    available: "2026-01-27T00:00",
    due: "2026-02-10T23:59",
    until: "2026-02-10T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Analyze a series of transition metal coordination compounds. For each, determine the oxidation state of the metal center, identify the ligand types, apply IUPAC nomenclature, and predict whether the complex is likely to be paramagnetic or diamagnetic based on d-electron count.",
  },
  {
    _id: "A502",
    title: "Crystal Field Theory Problem Set",
    course: "RS105",
    available: "2026-02-17T00:00",
    due: "2026-03-03T23:59",
    until: "2026-03-10T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Apply crystal field theory to a set of octahedral, tetrahedral, and square planar complexes. Calculate crystal field stabilization energies, predict color and magnetic properties, and explain observed trends in a short written discussion.",
  },
  {
    _id: "A503",
    title: "Inorganic Synthesis Lab Report",
    course: "RS105",
    available: "2026-03-17T00:00",
    due: "2026-04-07T23:59",
    until: "2026-04-21T23:59",
    points: 100,
    group: "LAB_REPORTS",
    gradeType: "PERCENTAGE",
    submissionType: "IN_PERSON",
    onlineEntryOptions: {
      textEntry: false,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Submit a formal report on the synthesis and characterization of an inorganic coordination complex completed in lab. Include the reaction scheme, characterization data (IR, UV-Vis), percent yield, and a discussion comparing your results to literature values.",
  },
  {
    _id: "A601",
    title: "Thermodynamics Problem Set",
    course: "RS106",
    available: "2026-01-22T00:00",
    due: "2026-02-05T23:59",
    until: "2026-02-05T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Work through problems on the first and second laws of thermodynamics as applied to chemical systems. Topics include enthalpy and entropy calculations, Gibbs free energy, and equilibrium constants. Show all derivations and unit analysis clearly.",
  },
  {
    _id: "A602",
    title: "Quantum Mechanics Assignment",
    course: "RS106",
    available: "2026-02-12T00:00",
    due: "2026-02-26T23:59",
    until: "2026-03-05T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Solve problems involving the particle in a box, harmonic oscillator, and hydrogen atom wavefunctions. Interpret the physical meaning of each solution and apply the results to explain trends in molecular spectroscopy and atomic orbital energies.",
  },
  {
    _id: "A603",
    title: "Reaction Kinetics Lab Report",
    course: "RS106",
    available: "2026-03-12T00:00",
    due: "2026-04-02T23:59",
    until: "2026-04-16T23:59",
    points: 100,
    group: "LAB_REPORTS",
    gradeType: "PERCENTAGE",
    submissionType: "IN_PERSON",
    onlineEntryOptions: {
      textEntry: false,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Everyone",
    description:
      "Analyze kinetic data collected during the lab experiment on reaction rate dependence. Determine the rate law, rate constant, and activation energy using graphical methods. Discuss how temperature and concentration influenced the observed reaction rates.",
  },
  {
    _id: "A701",
    title: "Tengwar Script Transcription",
    course: "RS107",
    available: "2026-01-20T00:00",
    due: "2026-02-03T23:59",
    until: "2026-02-03T23:59",
    points: 75,
    group: "ASSIGNMENTS",
    gradeType: "RAW_TOTAL",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: true,
    },
    assignTo: "Section 001",
    description:
      "Transcribe the provided passage from Common Speech into Tengwar script using the mode of Gondor. Annotate your transcription with a key identifying each tengwa and tehta used, and include a brief paragraph on the historical context in which this mode was employed.",
  },
  {
    _id: "A702",
    title: "Sindarin Translation Exercise",
    course: "RS107",
    available: "2026-02-10T00:00",
    due: "2026-02-24T23:59",
    until: "2026-03-03T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Section 001",
    description:
      "Translate five short passages from Sindarin into English and five from English into Sindarin. Apply correct mutation rules and verb conjugation throughout. For each translation, include a word-by-word gloss and a brief note on any grammatical structures of particular interest.",
  },
  {
    _id: "A703",
    title: "Comparative Linguistic Analysis",
    course: "RS107",
    available: "2026-03-10T00:00",
    due: "2026-03-31T23:59",
    until: "2026-04-07T23:59",
    points: 125,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: true,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Section 001",
    description:
      "Write a comparative essay examining at least two languages of Middle-earth — chosen from Quenya, Sindarin, Khuzdul, and the Black Speech — with respect to phonology, morphology, and cultural function. Draw on primary texts and course readings to support your analysis.",
  },
  {
    _id: "A801",
    title: "Council of Elrond Case Study",
    course: "RS108",
    available: "2026-01-27T00:00",
    due: "2026-02-10T23:59",
    until: "2026-02-10T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: true,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Section 002",
    description:
      "Analyze the Council of Elrond as a diplomatic event. Identify the representatives of each race, their stated interests and underlying motivations, and the negotiation strategies employed. Evaluate the outcome of the Council against the principles of consensus-based multilateral diplomacy covered in Module 2.",
  },
  {
    _id: "A802",
    title: "Inter-species Alliance Analysis",
    course: "RS108",
    available: "2026-02-17T00:00",
    due: "2026-03-03T23:59",
    until: "2026-03-10T23:59",
    points: 100,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Section 002",
    description:
      "Select one inter-species alliance from Middle-earth history (e.g., Men and Elves in the Last Alliance, Rohirrim and Gondor at Pelennor) and analyze its formation, maintenance, and outcome. Apply at least two theoretical frameworks from the course to explain why the alliance succeeded or failed.",
  },
  {
    _id: "A803",
    title: "Diplomatic Resolution Essay",
    course: "RS108",
    available: "2026-03-17T00:00",
    due: "2026-04-07T23:59",
    until: "2026-04-21T23:59",
    points: 150,
    group: "ASSIGNMENTS",
    gradeType: "PERCENTAGE",
    submissionType: "ONLINE",
    onlineEntryOptions: {
      textEntry: true,
      websiteUrl: false,
      mediaRecordings: false,
      studentAnnotation: false,
    },
    assignTo: "Section 002",
    description:
      "Propose a diplomatic resolution to a conflict of your choice from Middle-earth history, imagining an alternative outcome. Your essay must apply course frameworks to design a negotiation process, identify potential mediators, and assess the long-term viability of your proposed resolution. Minimum 1500 words.",
  },
];
