export default [
  {
    _id: "Q101",
    title: "Rocket Propulsion Fundamentals",
    course: "RS101",
    description:
      "This quiz covers the fundamental principles of rocket propulsion including Newton's laws, thrust generation, and propellant types.",
    quizType: "PRACTICE",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimit: 30,
    multipleAttempts: true,
    howManyAttempts: 3,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2026-05-01T23:59:00",
    availableDate: "2026-04-01T00:00:00",
    untilDate: "2026-05-01T23:59:00",
    published: true,
    questions: [
      {
        _id: "Q101-Q1",
        title: "Newton's Third Law",
        type: "MULTIPLE_CHOICE",
        points: 10,
        question:
          "Which of Newton's laws most directly explains rocket propulsion?",
        choices: [
          { _id: "Q101-Q1-C1", text: "First Law (Inertia)", isCorrect: false },
          {
            _id: "Q101-Q1-C2",
            text: "Second Law (F = ma)",
            isCorrect: false,
          },
          {
            _id: "Q101-Q1-C3",
            text: "Third Law (Action-Reaction)",
            isCorrect: true,
          },
          {
            _id: "Q101-Q1-C4",
            text: "Law of Universal Gravitation",
            isCorrect: false,
          },
        ],
        correctAnswer: null,
        correctResponses: [],
      },
      {
        _id: "Q101-Q2",
        title: "Specific Impulse",
        type: "MULTIPLE_CHOICE",
        points: 10,
        question: "What does specific impulse (Isp) measure?",
        choices: [
          {
            _id: "Q101-Q2-C1",
            text: "The total thrust of an engine",
            isCorrect: false,
          },
          {
            _id: "Q101-Q2-C2",
            text: "The efficiency of a propellant",
            isCorrect: true,
          },
          {
            _id: "Q101-Q2-C3",
            text: "The weight of the rocket",
            isCorrect: false,
          },
          {
            _id: "Q101-Q2-C4",
            text: "The burn rate of the fuel",
            isCorrect: false,
          },
        ],
        correctAnswer: null,
        correctResponses: [],
      },
      {
        _id: "Q101-Q3",
        title: "Solid vs Liquid Propellant",
        type: "TRUE_OR_FALSE",
        points: 10,
        question:
          "Solid propellant rockets can be throttled and shut down after ignition.",
        choices: [],
        correctAnswer: false,
        correctResponses: [],
      },
      {
        _id: "Q101-Q4",
        title: "Rocket Equation",
        type: "FILL_IN_THE_BLANK",
        points: 10,
        question:
          "The Tsiolkovsky rocket equation relates delta-v to exhaust velocity and the _____ ratio.",
        choices: [],
        correctAnswer: null,
        correctResponses: ["mass", "mass ratio"],
      },
      {
        _id: "Q101-Q5",
        title: "Thrust Direction",
        type: "TRUE_OR_FALSE",
        points: 10,
        question:
          "A rocket engine produces thrust in the opposite direction of the exhaust gases.",
        choices: [],
        correctAnswer: true,
        correctResponses: [],
      },
    ],
  },
  {
    _id: "Q102",
    title: "Combustion Chamber Design",
    course: "RS101",
    description:
      "Test your knowledge of combustion chamber principles, flame temperatures, and combustion instabilities.",
    quizType: "PRACTICE",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: false,
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: true,
    dueDate: "2026-05-15T23:59:00",
    availableDate: "2026-04-15T00:00:00",
    untilDate: "2026-05-15T23:59:00",
    published: true,
    questions: [
      {
        _id: "Q102-Q1",
        title: "Combustion Temperature",
        type: "MULTIPLE_CHOICE",
        points: 15,
        question:
          "What is the primary factor that determines the adiabatic flame temperature in a rocket combustion chamber?",
        choices: [
          {
            _id: "Q102-Q1-C1",
            text: "Chamber pressure",
            isCorrect: false,
          },
          {
            _id: "Q102-Q1-C2",
            text: "Propellant combination and mixture ratio",
            isCorrect: true,
          },
          {
            _id: "Q102-Q1-C3",
            text: "Nozzle geometry",
            isCorrect: false,
          },
          {
            _id: "Q102-Q1-C4",
            text: "Ambient temperature",
            isCorrect: false,
          },
        ],
        correctAnswer: null,
        correctResponses: [],
      },
      {
        _id: "Q102-Q2",
        title: "Combustion Instability",
        type: "TRUE_OR_FALSE",
        points: 15,
        question:
          "Combustion instability in a rocket engine can lead to catastrophic failure.",
        choices: [],
        correctAnswer: true,
        correctResponses: [],
      },
      {
        _id: "Q102-Q3",
        title: "Oxidizer Name",
        type: "FILL_IN_THE_BLANK",
        points: 20,
        question:
          "LOX stands for Liquid ______.",
        choices: [],
        correctAnswer: null,
        correctResponses: ["oxygen", "Oxygen"],
      },
    ],
  },
  {
    _id: "Q103",
    title: "Nozzle Design Principles",
    course: "RS101",
    description:
      "Quiz on converging-diverging nozzle design, flow conditions, and performance optimization.",
    quizType: "PRACTICE",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: false,
    timeLimit: 25,
    multipleAttempts: true,
    howManyAttempts: 2,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2026-06-01T23:59:00",
    availableDate: "2026-05-15T00:00:00",
    untilDate: "2026-06-01T23:59:00",
    published: false,
    questions: [
      {
        _id: "Q103-Q1",
        title: "De Laval Nozzle",
        type: "MULTIPLE_CHOICE",
        points: 10,
        question:
          "At what point in a converging-diverging nozzle does the flow reach Mach 1?",
        choices: [
          { _id: "Q103-Q1-C1", text: "At the inlet", isCorrect: false },
          { _id: "Q103-Q1-C2", text: "At the throat", isCorrect: true },
          { _id: "Q103-Q1-C3", text: "At the exit", isCorrect: false },
          {
            _id: "Q103-Q1-C4",
            text: "At the midpoint of the diverging section",
            isCorrect: false,
          },
        ],
        correctAnswer: null,
        correctResponses: [],
      },
      {
        _id: "Q103-Q2",
        title: "Nozzle Expansion",
        type: "TRUE_OR_FALSE",
        points: 10,
        question:
          "An over-expanded nozzle produces more thrust than a perfectly expanded nozzle at the same altitude.",
        choices: [],
        correctAnswer: false,
        correctResponses: [],
      },
      {
        _id: "Q103-Q3",
        title: "Throat Condition",
        type: "FILL_IN_THE_BLANK",
        points: 10,
        question:
          "The condition where flow velocity equals the local speed of sound is called _____ flow.",
        choices: [],
        correctAnswer: null,
        correctResponses: ["choked", "sonic"],
      },
    ],
  },
  {
    _id: "Q201",
    title: "Airfoil Theory Quiz",
    course: "RS102",
    description:
      "Covers the basics of airfoil aerodynamics, lift generation, and boundary layer theory.",
    quizType: "PRACTICE",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: true,
    howManyAttempts: 2,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2026-05-10T23:59:00",
    availableDate: "2026-04-01T00:00:00",
    untilDate: "2026-05-10T23:59:00",
    published: true,
    questions: [
      {
        _id: "Q201-Q1",
        title: "Bernoulli's Principle",
        type: "MULTIPLE_CHOICE",
        points: 10,
        question:
          "According to Bernoulli's principle, what happens to pressure when airflow velocity increases?",
        choices: [
          { _id: "Q201-Q1-C1", text: "Pressure increases", isCorrect: false },
          { _id: "Q201-Q1-C2", text: "Pressure decreases", isCorrect: true },
          {
            _id: "Q201-Q1-C3",
            text: "Pressure stays the same",
            isCorrect: false,
          },
          {
            _id: "Q201-Q1-C4",
            text: "Pressure oscillates",
            isCorrect: false,
          },
        ],
        correctAnswer: null,
        correctResponses: [],
      },
      {
        _id: "Q201-Q2",
        title: "Angle of Attack",
        type: "TRUE_OR_FALSE",
        points: 10,
        question:
          "Increasing the angle of attack always increases lift on an airfoil.",
        choices: [],
        correctAnswer: false,
        correctResponses: [],
      },
      {
        _id: "Q201-Q3",
        title: "Boundary Layer",
        type: "FILL_IN_THE_BLANK",
        points: 10,
        question:
          "The thin layer of air close to the airfoil surface where viscous effects are significant is called the _____ layer.",
        choices: [],
        correctAnswer: null,
        correctResponses: ["boundary"],
      },
      {
        _id: "Q201-Q4",
        title: "Drag Types",
        type: "MULTIPLE_CHOICE",
        points: 10,
        question:
          "Which type of drag is caused by the generation of lift?",
        choices: [
          { _id: "Q201-Q4-C1", text: "Parasitic drag", isCorrect: false },
          { _id: "Q201-Q4-C2", text: "Induced drag", isCorrect: true },
          { _id: "Q201-Q4-C3", text: "Wave drag", isCorrect: false },
          { _id: "Q201-Q4-C4", text: "Form drag", isCorrect: false },
        ],
        correctAnswer: null,
        correctResponses: [],
      },
    ],
  },
  {
    _id: "Q202",
    title: "Supersonic Flow Fundamentals",
    course: "RS102",
    description:
      "Test your understanding of compressible flow, shock waves, and supersonic aerodynamics.",
    quizType: "PRACTICE",
    assignmentGroup: "EXAMS",
    shuffleAnswers: true,
    timeLimit: 45,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: false,
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: true,
    dueDate: "2026-05-20T23:59:00",
    availableDate: "2026-05-01T00:00:00",
    untilDate: "2026-05-20T23:59:00",
    published: true,
    questions: [
      {
        _id: "Q202-Q1",
        title: "Mach Number",
        type: "FILL_IN_THE_BLANK",
        points: 15,
        question:
          "The ratio of the speed of an object to the speed of sound in the surrounding medium is called the _____ number.",
        choices: [],
        correctAnswer: null,
        correctResponses: ["mach", "Mach"],
      },
      {
        _id: "Q202-Q2",
        title: "Normal Shock",
        type: "TRUE_OR_FALSE",
        points: 15,
        question:
          "Across a normal shock wave, the flow transitions from supersonic to subsonic.",
        choices: [],
        correctAnswer: true,
        correctResponses: [],
      },
      {
        _id: "Q202-Q3",
        title: "Speed of Sound",
        type: "MULTIPLE_CHOICE",
        points: 20,
        question:
          "What primarily determines the speed of sound in an ideal gas?",
        choices: [
          { _id: "Q202-Q3-C1", text: "Pressure alone", isCorrect: false },
          { _id: "Q202-Q3-C2", text: "Density alone", isCorrect: false },
          {
            _id: "Q202-Q3-C3",
            text: "Temperature and gas properties",
            isCorrect: true,
          },
          { _id: "Q202-Q3-C4", text: "Altitude", isCorrect: false },
        ],
        correctAnswer: null,
        correctResponses: [],
      },
    ],
  },
  {
    _id: "Q301",
    title: "Spacecraft Subsystems Overview",
    course: "RS103",
    description:
      "Covers the major spacecraft subsystems including power, thermal control, propulsion, and communications.",
    quizType: "PRACTICE",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimit: 30,
    multipleAttempts: true,
    howManyAttempts: 2,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: "2026-05-15T23:59:00",
    availableDate: "2026-04-01T00:00:00",
    untilDate: "2026-05-15T23:59:00",
    published: true,
    questions: [
      {
        _id: "Q301-Q1",
        title: "Power Systems",
        type: "MULTIPLE_CHOICE",
        points: 10,
        question:
          "What is the most common power source for spacecraft in Earth orbit?",
        choices: [
          {
            _id: "Q301-Q1-C1",
            text: "Nuclear reactors",
            isCorrect: false,
          },
          { _id: "Q301-Q1-C2", text: "Solar panels", isCorrect: true },
          { _id: "Q301-Q1-C3", text: "Fuel cells", isCorrect: false },
          {
            _id: "Q301-Q1-C4",
            text: "Thermoelectric generators",
            isCorrect: false,
          },
        ],
        correctAnswer: null,
        correctResponses: [],
      },
      {
        _id: "Q301-Q2",
        title: "Thermal Control",
        type: "TRUE_OR_FALSE",
        points: 10,
        question:
          "In space, heat can only be rejected through radiation since there is no medium for convection.",
        choices: [],
        correctAnswer: true,
        correctResponses: [],
      },
      {
        _id: "Q301-Q3",
        title: "Orbit Type",
        type: "FILL_IN_THE_BLANK",
        points: 10,
        question:
          "A geostationary orbit has a period of approximately _____ hours.",
        choices: [],
        correctAnswer: null,
        correctResponses: ["24", "twenty-four"],
      },
      {
        _id: "Q301-Q4",
        title: "Attitude Control",
        type: "MULTIPLE_CHOICE",
        points: 10,
        question:
          "Which device is commonly used for fine attitude control in spacecraft?",
        choices: [
          { _id: "Q301-Q4-C1", text: "Reaction wheels", isCorrect: true },
          { _id: "Q301-Q4-C2", text: "Parachutes", isCorrect: false },
          { _id: "Q301-Q4-C3", text: "Ailerons", isCorrect: false },
          { _id: "Q301-Q4-C4", text: "Rudders", isCorrect: false },
        ],
        correctAnswer: null,
        correctResponses: [],
      },
      {
        _id: "Q301-Q5",
        title: "Communication Band",
        type: "TRUE_OR_FALSE",
        points: 10,
        question:
          "The S-band frequency range is commonly used for deep space communication.",
        choices: [],
        correctAnswer: false,
        correctResponses: [],
      },
    ],
  },
];
